apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: asr-gateway
  template:
    metadata:
      labels:
        app: asr-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.metrics.path | quote }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
    spec:
      containers:
        - name: asr-gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PHRASES_PATH
              value: {{ .Values.env.PHRASES_PATH | quote }}
            - name: CTI_DECISION_URL
              value: {{ .Values.env.CTI_DECISION_URL | quote }}
            - name: FUNASR_WS_URL
              value: {{ .Values.env.FUNASR_WS_URL | quote }}
            - name: ASR_MODE
              value: {{ .Values.env.ASR_MODE | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}