apiVersion: v1
kind: Service
metadata:
  name: asr-gateway
spec:
  selector:
    app: asr-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP