version: 1
languages: ["zh"]
classes:
  power_off:
    - "已关机"
    - "您拨打的用户.*关机"
    - "当前为关机状态"
  suspended:
    - "已停机"
    - "欠费停机"
  invalid_number:
    - "是空号"
    - "号码不存在"
    - "不是有效号码"
    - "号码有误"
  out_of_service:
    - "不在服务区"
    - "超出服务范围"
  busy:
    - "正在通话中"
    - "线路正忙"
    - "占线"
  voicemail:
    - "请在听到提示音后留言"
    - "语音信箱"
    - "嘟一声后开始录音"
  color_ring_back:
    - "彩铃"
    - "来电彩铃"
  operator_ivr:
    - "您拨打的电话暂时无法接通"
    - "暂时无法接通"